/**
 * utils/exportUtils.js
 *
 * Client-side export: Markdown, JSON, and PDF.
 *
 * PDF uses html2canvas + jspdf-style approach via the browser's
 * built-in print-to-PDF. No heavy dependency required.
 */

/**
 * Downloads a string as a file.
 */
function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Exports the AI response as a Markdown file.
 */
export function exportMarkdown(report) {
  const title = report?.title ?? "Financial Analysis";
  const sections = report?.sections ?? [];
  const reasoning = report?.rawReasoning ?? "";

  let md = `# ${title}\n\n`;
  md += `*Generated on ${report?.generatedAt ?? new Date().toISOString()}*\n\n`;

  if (report?.summary) {
    md += `## Executive Summary\n\n${report.summary}\n\n`;
  }

  if (report?.recommendation) {
    md += `**Recommendation:** ${report.recommendation}`;
    if (report.confidence) md += ` (${report.confidence} confidence)`;
    md += "\n\n";
  }

  if (report?.investmentScore !== null && report?.investmentScore !== undefined) {
    md += `**Investment Score:** ${report.investmentScore}/100\n\n`;
  }

  if (sections.length > 0) {
    for (const section of sections) {
      md += `## ${section.title}\n\n${section.content}\n\n`;
    }
  } else if (reasoning) {
    md += reasoning;
  }

  if (report?.keyPositives?.length > 0) {
    md += `## Key Positives\n\n`;
    report.keyPositives.forEach((p) => (md += `- ✅ ${p}\n`));
    md += "\n";
  }

  if (report?.keyNegatives?.length > 0) {
    md += `## Key Negatives\n\n`;
    report.keyNegatives.forEach((n) => (md += `- ⚠️ ${n}\n`));
    md += "\n";
  }

  md += `---\n*Generated by AI Investment Research Agent*\n`;

  const safeName = title.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 50);
  downloadFile(md, `${safeName}.md`, "text/markdown");
}

/**
 * Exports the report as a JSON file.
 */
export function exportJSON(report) {
  const title = report?.title ?? "Financial_Analysis";
  const safeName = title.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 50);
  downloadFile(
    JSON.stringify(report, null, 2),
    `${safeName}.json`,
    "application/json"
  );
}

/**
 * Exports the report as a PDF using the browser's print dialog.
 * Creates a styled print-friendly HTML document in a new window.
 */
export function exportPDF(report) {
  const title = report?.title ?? "Financial Analysis";
  const sections = report?.sections ?? [];
  const reasoning = report?.rawReasoning ?? "";

  let body = `<h1>${title}</h1>`;
  body += `<p style="color:#666;font-size:12px;">Generated on ${report?.generatedAt ?? new Date().toISOString()}</p>`;

  if (report?.summary) {
    body += `<h2>Executive Summary</h2><p>${report.summary}</p>`;
  }

  if (report?.recommendation) {
    body += `<p><strong>Recommendation:</strong> ${report.recommendation}`;
    if (report.confidence) body += ` (${report.confidence} confidence)`;
    body += `</p>`;
  }

  if (report?.investmentScore !== null && report?.investmentScore !== undefined) {
    body += `<p><strong>Investment Score:</strong> ${report.investmentScore}/100</p>`;
  }

  if (sections.length > 0) {
    for (const section of sections) {
      body += `<h2>${section.title}</h2>`;
      // Convert markdown-like content to basic HTML
      const content = section.content
        .replace(/^### (.+)$/gm, "<h3>$1</h3>")
        .replace(/^## (.+)$/gm, "<h2>$1</h2>")
        .replace(/^\- (.+)$/gm, "<li>$1</li>")
        .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
        .replace(/\n/g, "<br>");
      body += `<div>${content}</div>`;
    }
  } else if (reasoning) {
    body += `<div>${reasoning.replace(/\n/g, "<br>")}</div>`;
  }

  if (report?.keyPositives?.length > 0) {
    body += `<h2>Key Positives</h2><ul>`;
    report.keyPositives.forEach((p) => (body += `<li>✅ ${p}</li>`));
    body += `</ul>`;
  }

  if (report?.keyNegatives?.length > 0) {
    body += `<h2>Key Negatives</h2><ul>`;
    report.keyNegatives.forEach((n) => (body += `<li>⚠️ ${n}</li>`));
    body += `</ul>`;
  }

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    body { font-family: 'Inter', Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; line-height: 1.7; }
    h1 { color: #1a1a2e; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
    h2 { color: #4338ca; margin-top: 24px; }
    h3 { color: #6366f1; }
    table { border-collapse: collapse; width: 100%; margin: 12px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background: #f0f4ff; }
    li { margin: 4px 0; }
    strong { color: #312e81; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>${body}
  <hr>
  <p style="color:#999;font-size:11px;">Generated by AI Investment Research Agent</p>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 500);
  }
}

/**
 * Copies text to the clipboard.
 */
export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement("textarea");
    textarea.value = text;
    textarea.style.position = "fixed";
    textarea.style.opacity = "0";
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
    return true;
  }
}
